services:
  mysql-cinema:
    image: mysql:8.0
    container_name: mysql-cinema
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql-cinema-data:/var/lib/mysql
    networks:
      - internal-cinema
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  cinema-tickets:
    image: blagoyvelinov/cinema-tickets
    container_name: cinema-tickets
    restart: on-failure
    environment:
      db_host: ${db_host}
      db_port: 3306
      db_name: ${db_name}
      db_username: ${db_username}
      db_password: ${db_password}
      JWT_SECRET: ${JWT_SECRET}
      MY_PUBLIC_KEY: ${MY_PUBLIC_KEY}
      MY_SECRET_KEY: ${MY_SECRET_KEY}
      MAIL_SENDER: ${MAIL_SENDER}
    depends_on:
      mysql-cinema:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - internal-cinema

volumes:
  mysql-cinema-data:

networks:
  internal-cinema:
