spring:
  datasource:
#    url: ${AZURE_MYSQL_CONNECTIONSTRING}
    url: jdbc:mysql://${DB_HOST:cinema-tickets-app-server.mysql.database.azure.com}:3306/${DB_NAME:cinema-tickets-app-database}?useSSL=true&requireSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:adminUser@cinema-mysql}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: never

  application:
    name: CinemaTicketsAPI

server:
  port: ${PORT:8080}
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
