logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
        descriptor: TRACE

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cinema_tickets_11_august_2024?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    url: jdbc:mysql://mysql:3306/cinema_tickets_11_august_2024?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    password: ${db_password:}
    username: ${db_username:root}

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: never

  cinema_tickets:
    default:
      admin:
        pass: ${DEFAULT_ADMIN_PASS:123456}
    remember:
      me:
        key: ${REMEMBER_ME_KEY:123456}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

jwt:
  secret: ${JWT_SECRET:ThisIsAVeryLongSuperSecretKeyThatIsAtLeast32Chars}
  expiration: 604800000




mail:
  cinema_tickets: c_tickets@gmail.com
  host: localhost
  port: 1025
  username: ${MAIL_USER:softuni}
  password: ${MAIL_PASSWORD:softuni}

  version: "3"
  services:
    mail-hog:
      image: mailhog/mailhog:latest
      restart: always
      ports:
        - 1025:1025
        - 8025:8025

  movies:
    api:
      baseUrl: "http://localhost:8081"