logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
        descriptor: TRACE

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db_host:localhost}:3306/cinema_tickets_11_august_2024?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    password: ${db_password:}
    username: ${db_username:root}

  profiles:
    active: dev

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: never

  cinema_tickets:
    default:
      admin:
        pass: ${DEFAULT_ADMIN_PASS:123456}
    remember:
      me:
        key: ${REMEMBER_ME_KEY:123456}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  mail:
    host: in-v3.mailjet.com
    port: 587
    username: ${MY_PUBLIC_KEY}
    password: ${MY_SECRET_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mail:
  cinema_tickets: "my.cinematockets@gmail.com"

jwt:
  secret: ${JWT_SECRET:ThisIsAVeryLongSuperSecretKeyThatIsAtLeast32Chars}
  expiration: 604800000


  movies:
    api:
      baseUrl: "http://localhost:8081"